# Generated by Django 5.0.2 on 2026-02-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin'), ('SHOPPER', 'Personal Shopper'), ('CROWDSOURCER', 'Crowdsourcer'), ('INTEGRATOR', 'Integrator')], default='CUSTOMER', max_length=20),
        ),
    ]
