# Generated by Django 5.0.2 on 2026-04-11 13:55

from django.contrib.auth.hashers import make_password
from django.db import migrations


def seed_admin_user(apps, schema_editor):
    User = apps.get_model("users", "User")
    admin_email = "admin@howmuch.com"
    admin_password = "Admin1234!"

    user, _ = User.objects.get_or_create(
        username=admin_email,
        defaults={"email": admin_email},
    )

    user.email = admin_email
    user.is_staff = True
    user.is_superuser = True
    user.is_active = True
    user.user_type = "ADMIN"
    user.is_verified = True
    user.password = make_password(admin_password)
    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_user_type"),
    ]

    operations = [
        migrations.RunPython(seed_admin_user, migrations.RunPython.noop),
    ]
