# Generated by Django 5.0.2 on 2026-03-28 08:59

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('nin', models.CharField(max_length=20, verbose_name='National Identification Number')),
                ('store_address', models.TextField()),
                ('store_city', models.CharField(max_length=100)),
                ('store_state', models.CharField(max_length=100)),
                ('store_landmark', models.CharField(blank=True, help_text='Nearby landmark for easier location', max_length=255)),
                ('store_image_1', cloudinary.models.CloudinaryField(blank=True, help_text='Front view of store', max_length=255, null=True, verbose_name='image')),
                ('store_image_2', cloudinary.models.CloudinaryField(blank=True, help_text='Inside view of store', max_length=255, null=True, verbose_name='image')),
                ('store_image_3', cloudinary.models.CloudinaryField(blank=True, help_text='Products on display', max_length=255, null=True, verbose_name='image')),
                ('years_in_business', models.PositiveIntegerField(default=0, help_text='Years operating this business')),
                ('products_sold', models.TextField(blank=True, help_text='Main products sold (comma separated)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vendors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Verification',
                'verbose_name_plural': 'Vendor Verifications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
