# Generated by Django 5.0.2 on 2026-03-30 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0002_pricehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('offer_made', 'Offer Made'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('buyer_notes', models.TextField(blank=True, help_text='Notes from buyer when creating request')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if buyer rejects offer')),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_state', models.CharField(blank=True, max_length=100)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'user_type': 'BUYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.URLField(blank=True, null=True)),
                ('size_label', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('listed_price', models.DecimalField(decimal_places=2, help_text='Price at time of request', max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, help_text='Buyer notes for this specific item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_items', to='pricing.vendorlisting')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchaserequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, help_text='Optional service/handling fee', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=12)),
                ('estimated_delivery', models.CharField(blank=True, help_text="e.g. '2-3 hours', 'Same day', 'Tomorrow'", max_length=255)),
                ('message', models.TextField(blank=True, help_text='Message from vendor to buyer')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='orders.purchaserequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.DecimalField(decimal_places=2, help_text="Vendor's offered price per unit", max_digits=12)),
                ('notes', models.TextField(blank=True, help_text="Vendor notes for this item e.g. 'Out of stock, substituted'")),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_prices', to='orders.requestitem')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='orders.vendoroffer')),
            ],
            options={
                'unique_together': {('offer', 'request_item')},
            },
        ),
    ]
