# Generated by Django 5.0.2 on 2026-04-01 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='fulfillment_status',
            field=models.CharField(choices=[('none', 'Not Started'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='buyer_notes',
            field=models.TextField(blank=True, help_text='Notes from customer when creating request'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason if customer rejects offer'),
        ),
    ]
