# Generated by Django 5.0.2 on 2026-02-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketprice',
            name='image_proof',
        ),
        migrations.AddField(
            model_name='marketprice',
            name='proof_image_1',
            field=models.ImageField(help_text='Required: 1st angle', null=True, upload_to='market_prices/proofs/'),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='proof_image_2',
            field=models.ImageField(help_text='Required: 2nd angle', null=True, upload_to='market_prices/proofs/'),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='proof_image_3',
            field=models.ImageField(help_text='Required: 3rd angle', null=True, upload_to='market_prices/proofs/'),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='proof_image_4',
            field=models.ImageField(help_text='Required: 4th angle', null=True, upload_to='market_prices/proofs/'),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='proof_image_5',
            field=models.ImageField(blank=True, help_text='Optional: 5th angle', null=True, upload_to='market_prices/proofs/'),
        ),
    ]
