# Generated by Django 5.0.2 on 2026-02-26 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0002_remove_marketprice_image_proof_and_more'),
        ('products', '0003_sizerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketprice',
            name='product_name',
            field=models.CharField(default='', help_text='Name of the product entered by crowdsourcer', max_length=255),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='products.product'),
        ),
    ]
