# Generated by Django 5.0.2 on 2026-03-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0004_crowdsourcedsubmission_crowdsourceditem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsourcedsubmission',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
    ]
