# Generated by Django 5.0.2 on 2026-02-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['unit', 'value']},
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_by',
            field=models.ForeignKey(blank=True, help_text='Null if added directly by admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productsize',
            name='label',
            field=models.CharField(blank=True, help_text="Auto-generated if left blank e.g. '5kg'", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.productsize'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Auto-generated if left blank', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.unitofmeasurement'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
    ]
