# Generated by Django 5.0.2 on 2026-04-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopperprofile',
            name='nin',
            field=models.CharField(blank=True, help_text='National Identification Number', max_length=11),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Shopper profile photo', null=True, upload_to='shopper_photos/'),
        ),
    ]
